[package]
name = "pg_replicate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = { git = "https://github.com/MaterializeInc/rust-postgres" }
postgres-protocol = { git = "https://github.com/MaterializeInc/rust-postgres" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
thiserror = "1.0"
bytes = "1.0"

[dev-dependencies]
parquet = "50"
tempfile = "3.10"
arrow-array = "50"
