source:
  postgres:
    host: "localhost"
    port: 5432
    name: "postgres"
    username: "postgres"
    slot_name: "replicator_slot"
    publication: "replicator_publication"
destination:
  big_query:
    project_id: "project-id"
    dataset_id: "dataset-id"
