source:
  Postgres:
    host: "localhost"
    port: 5432
    name: "postgres"
    username: "postgres"
    slot_name: "replicator_slot"
    publication: "replicator_publication"
sink:
  BigQuery:
    project_id: "project-id"
    dataset_id: "dataset-id"
